The first experiment helped me notice my emotions and what triggered them in a way I hadn’t before. Usually, I ignore how I feel, but tracking my feelings for a week revealed patterns I might have missed. I realized that small daily interactions could have a bigger impact on my mood than I thought. Although I worked alone, comparing my results with others showed how different everyone’s approach was, and it made me appreciate the diversity in how people process and express their emotions.
Reflecting on the week, I realized how valuable it is to pause and notice emotions rather than just letting them pass by. Tracking them revealed new patterns and perspectives on my own behavior, including sources of stress or unexpected happiness. I want to keep using these self-awareness techniques because I believe they can help me better understand myself and improve my relationships with others.
This experiment showed me that data is personal, not just numbers. Recording my feelings made me wonder if data can really capture what it means to be human, or if it oversimplifies emotions in the process. I’m now interested in visualizations that show the complexity of feelings, and how uncertainty and change are a normal part of emotional life.
My work reinforced that data isn’t neutral. Tracking and visualizing emotions showed how data collection shapes the story. What you choose to record, and how you choose to represent it, can change the meaning entirely. My approach was abstract and expressive, focusing on mood and form instead of traditional charts, and I found this allowed me to capture nuances that numbers alone might miss.
I want to blend personal and external data in meaningful visualizations, using generative and abstract forms to show emotion and change. Feedback on my last submission made me realize I need to connect my experiments more clearly to datasets and technical methods.
​

For my project, I want to explore friendships and the different connections people have. In my journal, I mapped my own influences. I imagine a future where devices track our social interactions, collecting data on how we communicate and feel around others. This could help us understand our relationships, but also raises privacy concerns and questions about whether data can truly measure complex bonds.
People rarely share their feelings about others in a way that can be compared, so live-tracking emotions would be new. I could visualize this with shapes and colors, maybe using a kaleidoscope pattern where each relationship affects the overall design. This would highlight which connections matter most and how they change over time.
My project ties into data humanism and how everyday experiences, like friendships and emotions, become data, even though these aren’t usually measured.
​


The final visualization will likely be interactive, using shapes, colors, and movement. It might use the kaleidoscope idea again, letting relationships and emotions shape the visuals as they change over time.
This project questions whether data can really capture human relationships or if measuring them oversimplifies what makes them unique.
I hope viewers see their relationships differently and consider how much of their lives could be tracked or measured.
